### PR TITLE
Addition of Putty-Clay model and PDE support

### PR DESCRIPTION
**Pull request by MattArran**
Added a model corresponding to a Goodwin-adjacent model, with a putty-clay production function, from Akerlof and Stiglitz (1969), and changed the code base to support this model. In the paper's model, investors select from technologies with different capital-labor ratios, to maximise profits based on current wages, but the capital-labor ratio is fixed at the point of investment. Consequently, potential employment is distributed at any time over machines of varying capital-labor ratio, with the distribution evolving as a partial differential equation. This model does not yet support multiple parallel systems.

To implement the model, support's been added in `set_dparam`, `reset`, `get_variables_compact`, `get_summary`, and `class_checks` for:
- `np.ndarray` parameters and variables
- multi-line non-lambda `'func'` definitions
- a `'pde`' equation type
These features are not yet supported in analysis and plotting code.

`def_fields` has been updated with the new model's variables and parameters and with corrected dimensions and units (fixing issue #85).

Ref:
- Akerlof, G. A. and Stiglitz, J. E., 1969. 'Capital, Wages and Structural Unemployment', The Economic Journal, Vol. 79, No. 314 (http://www.jstor.org/stable/2230168)

### CODE REVIEW

**Comment by Didou09** [comment]
Great job, thank you @MattArran, this looks like a clean PR
From your code changes I can tell you are not new to contributing to Python projects, the code seems clean and the PR is well-documented, thank you for that.

Since you are a first-time contributor to this particular repo, both @DaluS and me are going to review your contribution before approving it (the validation process for subsequent contributions will be faster, but for the first time we'll try to go through all of it).
Since both @DaluS  and I are on holidays right now, it may take a bot of time, sorry for the timing, but we'll discuss it as soon as we get back !

Also we're also in the middle of a small restructuration of some parts of the code (cf. other PRs awaiting), so we might prefer to finsh the restructuring before we merge your PR. I guess you can expect a ~1 week delay approximately.

Also, if I may risk a first comment, I see that your PR adresses not only the addition of a new model, but also a few other minor fixes like the units in `_def_fields.py` (cf. issue #85 that you reported). 
For future contributions, may we ask that you submit such independent fixes in separate, dedicated PRs ? 
We tend to prefer small, independent and well-focused PR whenever possible.

We'll get back to you in few days, thanks again!

**Comment by MattArran** [comment]
Hi @Didou09! Yep, no problem about the delay; there's no rush, so don't feel obliged to take any time out from your holiday to review the changes. I understand the preference for smaller, single-purpose PRs, so am sorry for the bundled fix of dimensions & units and for the refactoring of `Hub['dmisc']['model']` that I've just committed (afraid I'd made changes before I saw your reply). I'll set up separate branches in future and should be able to help with reviews to ameliorate the impact on integration. Nice to be contributing to a well-managed project!

**Comment by DaluS** [comment]
Thanks Matt, looks like a lot of great features ! 
I have to admit I didn't expected you to work on it as a developer ( I was expectif user/models that are compatible with the formalism) I'd have given you more info... 
I'll spend more time on it next week (just try to read it this week), simply I realised that you started on the "old formalism" and not the new one ( that can be found in `NewMain` ). As Didier is improving it and creating an hybrid version, We'll clean the core first and then add your improvement on it. I think you implemented PDE in a way I was not thinking (I was thinking about multisectorial formalism to be what you've done), I'd like to discuss it with you later also ! 

I give you feedback on Monday I guess, hope everything is fine in DC in the meantime :) (Brittany is cold, which is great)

**Comment by MattArran** [comment]
Closing this because it's well out of date and the PDE support has now been implemented in the main development branch. I'll look at implementing the Putty-Clay models within that version and see whether any further development's necessary to permit that.

**Comment by DaluS** [comment]
@MattArran PDE has not been implemented since, I'll do it this week.

**Comment by MattArran** [comment]
@DaluS Ah, must have misremembered you saying it was implemented. I'm not sure how much time I can spare, but let me know if I can help.

**Pull request closed without merging**
