### PR TITLE
Issue006 choice of system of equations

### PR DESCRIPTION
**Pull request by Didou09**
!!!!! WORK IN PROGRESS, INTERMEDIATE PR JUST TO KEEP YOU GUYS UPDATED !!!!!!

Motivation:
--------------
* This branch is here to handle the following issues:
   - Allow the user to choose a set of equation from input arguments (instead of hard-coded ones), issue #6 
   - It aims at doing it by implementing a generic `Solver` class (inspired from @DaluS  already-implemented classes)
   - This work will then facilitate the task for issue #3, which will be the natural next step
* In its current version it is not finished, I will finish it either late on Friday or early next week
* However, it implements new classes and modules and functions, but it does not change or break any of the existing code
* More importantly it does not break the existing unit tests, so it seems safe to merge (if you want to)
* It allows to modify a dict of parameters while ensuring consistency
* It provides a method to print a summary of the solver content

Example:
------------
```
In [1]: import _class

In [2]: sol = _class.Solver()

In [3]: sol.set_dparam()

In [4]: sol.set_dvar()

In [5]: sol.get_summary()
parameter  value                 units       group        comment                                                                  
---------  --------------------  ----------  -----------  -------------------------------------------------------------------------
Tmax       100                   time steps  Numerical    Duration of simulation                                                   
Nx         1                     None        Numerical    Number of similar systems evolving in parrallel                          
dt         0.01                  None        Numerical    Timestep (fixed timestep method)                                         
Tstore     0.01                  None        Numerical    Time between storages (if StorageMode=full, it goes to dt)               
Nt         10000                 None        Numerical    Number of temporal iteration                                             
Ns         10001                 None        Numerical    Number of elements stored                                                
verb       True                  None        Numerical    flag indicating whether to print intermediate info                       
storage    full                  None        Numerical    flag indicating which time steps to store                                
save       True                  None        Numerical    flag indicating whether to save output data                              
beta       0.025                 y^-1        Population   Rate of population growth                                                
PopSat     10000                 None        Population   Ratio between initial and maximal population                             
alpha      0.02                  y^-1        Population   Rate of productivity increase                                            
delta1     0.005                 y^-1        Capital      Rate of WORKING capital depletion                                        
delta2     0.005                 y^-1        Capital      Rate of ALL capital depletion                                            
nu         3                     None        Production   Kapital to output ratio (cf. Leontiev). !! IN CES its 1/A !!             
eta        1000                  None        Production   CES Only eta = 1/(1+substituability)                                     
b          5                     None        Production   CES parameter : capital part of the production                           
z          1                     None        Production   Markup on salary estimation                                              
r          0.03                  None        Prices       Interest at the bank                                                     
etaP       0.192                 None        Prices       Typical rate for inflation                                               
muP        1.3                   None        Prices       Mark-up of price                                                         
gammaP     1                     None        Prices       Money-illusion                                                           
phinul     0.04                  None        Philips      Unemployement rate at which there is no salary increase with no inflation
k0         -0.0065               None        Keen                                                                                  
k1         0.006737946999085467  None        Keen                                                                                  
k2         20                    None        Keen                                                                                  
div0       0.138                 None        Dividends    Part of GDP as dividends when pi=0                                       
div1       0.473                 None        Dividends    Slope                                                                    
g1         0.0                   None        Coupling     GLOBAL EFFECTS OF LAMBDA (Mean field)                                    
g2         0.0                   None        Coupling     WITH NEIGHBORS EFFECTS OF LAMBDA (field)                                 
muI        0.0                   None        Coupling                                                                              
muN        0.0                   None        Coupling                                                                              
tauR       2.0                   y           RelaxBuffer  Typical time for recruitement                                            
tauF       0.1                   y           RelaxBuffer  Typical time for firing                                                  
tauL       2.0                   y           RelaxBuffer  Typical time for employement information                                 
tauK       2.0                   y           RelaxBuffer  Typical time on new capital integration                                  
theta      2.6                   None        Gemmes       Convexity on abattement cost function                                    
dsigma     -0.001                None        Gemmes       Variation rate of the growth of emission intensity                       
dPBS       -0.005                None        Gemmes       Growth rate of back-stop technology price                                
dPc        0.0                   None        Gemmes       Growth rate of back-stop technology price                                
dEland     -0.022                None        Gemmes       Growth rate of land use change in CO2 emission                           
pi1        0.0                   None        Damage       Linear temperature impact                                                
pi2        0.00236               None        Damage       Quadratic temperature impact                                             
pi3        5.07e-06              None        Damage       Weitzmann Damage temperature impact                                      
zeta       6.754                 None        Damage       Weitzmann impact                                                         
fk         0.3333333333333333    None        Damage       Fraction of environmental damage                                         
Phi12      0.024                 None        Climate      Transfer of carbon from atmosphere to biosphere                          
Phi23      0.001                 None        Climate      Transfer from biosphere to stock                                         
C          10.204081632653061    None        Climate      Heat capacity of fast-paced climate                                      
C0         3.52                  None        Climate      Heat capacity of inertial component of climate                           
gamma      0.0176                None        Climate      Heat exchange coefficient between layer                                  
Tsens      3.1                   None        Climate      Climate sensitivity                                                      
dFexo      0                     None        Climate                                                                               
FexoMax    0                     None        Climate                                                                               
F2CO2      3.681                 W/m2        Climate      doubling CO2 impact on forced radiations                                 
CO2at_ini  851                   None        Climate                                                                               
CO2up_ini  460                   None        Climate                                                                               
CO2lo_ini  1740                  None        Climate                                                                               
T_ini      0                     None        Climate                                                                               

variable  shape       units  comment
--------  ----------  -----  -------
a         (10000, 1)                
N         (10000, 1)                
K         (10000, 1)                
W         (10000, 1)                
D         (10000, 1)                



In [6]: sol.set_dparam(key='dt', value=0.1)

In [7]: sol.get_summary()
parameter  value                 units       group        comment                                                                  
---------  --------------------  ----------  -----------  -------------------------------------------------------------------------
Tmax       100                   time steps  Numerical    Duration of simulation                                                   
Nx         1                     None        Numerical    Number of similar systems evolving in parrallel                          
dt         0.1                   None        Numerical    Timestep (fixed timestep method)                                         
Tstore     0.1                   None        Numerical    Time between storages (if StorageMode=full, it goes to dt)               
Nt         1000                  None        Numerical    Number of temporal iteration                                             
Ns         1001                  None        Numerical    Number of elements stored                                                
verb       True                  None        Numerical    flag indicating whether to print intermediate info                       
storage    full                  None        Numerical    flag indicating which time steps to store                                
save       True                  None        Numerical    flag indicating whether to save output data                              
beta       0.025                 y^-1        Population   Rate of population growth                                                
PopSat     10000                 None        Population   Ratio between initial and maximal population                             
alpha      0.02                  y^-1        Population   Rate of productivity increase                                            
delta1     0.005                 y^-1        Capital      Rate of WORKING capital depletion                                        
delta2     0.005                 y^-1        Capital      Rate of ALL capital depletion                                            
nu         3                     None        Production   Kapital to output ratio (cf. Leontiev). !! IN CES its 1/A !!             
eta        1000                  None        Production   CES Only eta = 1/(1+substituability)                                     
b          5                     None        Production   CES parameter : capital part of the production                           
z          1                     None        Production   Markup on salary estimation                                              
r          0.03                  None        Prices       Interest at the bank                                                     
etaP       0.192                 None        Prices       Typical rate for inflation                                               
muP        1.3                   None        Prices       Mark-up of price                                                         
gammaP     1                     None        Prices       Money-illusion                                                           
phinul     0.04                  None        Philips      Unemployement rate at which there is no salary increase with no inflation
k0         -0.0065               None        Keen                                                                                  
k1         0.006737946999085467  None        Keen                                                                                  
k2         20                    None        Keen                                                                                  
div0       0.138                 None        Dividends    Part of GDP as dividends when pi=0                                       
div1       0.473                 None        Dividends    Slope                                                                    
g1         0.0                   None        Coupling     GLOBAL EFFECTS OF LAMBDA (Mean field)                                    
g2         0.0                   None        Coupling     WITH NEIGHBORS EFFECTS OF LAMBDA (field)                                 
muI        0.0                   None        Coupling                                                                              
muN        0.0                   None        Coupling                                                                              
tauR       2.0                   y           RelaxBuffer  Typical time for recruitement                                            
tauF       0.1                   y           RelaxBuffer  Typical time for firing                                                  
tauL       2.0                   y           RelaxBuffer  Typical time for employement information                                 
tauK       2.0                   y           RelaxBuffer  Typical time on new capital integration                                  
theta      2.6                   None        Gemmes       Convexity on abattement cost function                                    
dsigma     -0.001                None        Gemmes       Variation rate of the growth of emission intensity                       
dPBS       -0.005                None        Gemmes       Growth rate of back-stop technology price                                
dPc        0.0                   None        Gemmes       Growth rate of back-stop technology price                                
dEland     -0.022                None        Gemmes       Growth rate of land use change in CO2 emission                           
pi1        0.0                   None        Damage       Linear temperature impact                                                
pi2        0.00236               None        Damage       Quadratic temperature impact                                             
pi3        5.07e-06              None        Damage       Weitzmann Damage temperature impact                                      
zeta       6.754                 None        Damage       Weitzmann impact                                                         
fk         0.3333333333333333    None        Damage       Fraction of environmental damage                                         
Phi12      0.024                 None        Climate      Transfer of carbon from atmosphere to biosphere                          
Phi23      0.001                 None        Climate      Transfer from biosphere to stock                                         
C          10.204081632653061    None        Climate      Heat capacity of fast-paced climate                                      
C0         3.52                  None        Climate      Heat capacity of inertial component of climate                           
gamma      0.0176                None        Climate      Heat exchange coefficient between layer                                  
Tsens      3.1                   None        Climate      Climate sensitivity                                                      
dFexo      0                     None        Climate                                                                               
FexoMax    0                     None        Climate                                                                               
F2CO2      3.681                 W/m2        Climate      doubling CO2 impact on forced radiations                                 
CO2at_ini  851                   None        Climate                                                                               
CO2up_ini  460                   None        Climate                                                                               
CO2lo_ini  1740                  None        Climate                                                                               
T_ini      0                     None        Climate                                                                               

variable  shape       units  comment
--------  ----------  -----  -------
a         (10000, 1)                
N         (10000, 1)                
K         (10000, 1)                
W         (10000, 1)                
D         (10000, 1)                


```

### CODE REVIEW

**Comment by DaluS** [comment]
**About dictionnaries**

I really like your system, especially the way you plot it. It's an alternative/complement to what I've done with 'VariableDictionnary.py' (Which is for variables and plots)

* I would add in this dictionnary a way to define the same type of notation for variables (as done in 'VariableDictionnary.py'
* I would do a fusion between yours and my approach in 'VariableDictionnary.py' , adding a name column, and a category 'parameter' and 'variable' maybe on top of it ? 
* For the python-user, I would reduce what are inside these "megadictionnary" to only relevant variables/parameters (I've done a ugly but working version at the end of 'VariableDictionnary.py' ) 
* I would print numerical parameters in a separate section of the print
* I would use these informations inside the plots also to automatically generate them
* I saw that you define variables in '_def_variables.py' for each class. The names of variables are already defined in the class ( in 'self.variables' for each), no need to redefine each time for each module.

** About restructuration ** I tried to integrate what you've done in your code, but I think I would do it badly (I think you haven't finished comments and added to many functions that I could understand at once) so I let you finish the integratation !

**Comment by Didou09** [comment]
> **About dictionnaries**
> 
> I really like your system, especially the way you plot it. It's an alternative/complement to what I've done with 'VariableDictionnary.py' (Which is for variables and plots)
> 
> * I would add in this dictionnary a way to define the same type of notation for variables (as done in 'VariableDictionnary.py'

ok I'll do it

> * I would do a fusion between yours and my approach in 'VariableDictionnary.py' , adding a name column, and a category 'parameter' and 'variable' maybe on top of it ?

On the way :-)

> * For the python-user, I would reduce what are inside these "megadictionnary" to only relevant variables/parameters (I've done a ugly but working version at the end of 'VariableDictionnary.py' )

OK, I'll have a look

> * I would print numerical parameters in a separate section of the print

ok

> * I would use these informations inside the plots also to automatically generate them

Yes, on the way too

> * I saw that you define variables in '_def_variables.py' for each class. The names of variables are already defined in the class ( in 'self.variables' for each), no need to redefine each time for each module.

ok
> 
> **About restructuration** I tried to integrate what you've done in your code, but I think I would do it badly (I think you haven't finished comments and added to many functions that I could understand at once) so I let you finish the integration !

Yes, I need more time but I'll deliver a complete and working solution, taking into account your comments on the way.
It's usually better practice to let someone finish and then adjust if necessary.
Just focus on other parts of the code (independent if possible) in the mean time, like: plots, articles reproducibility, regionalization, new modules...

> 
> **In the meantime** I will work on the integration of new modules ( plots and set of equations )

That's good practice :-)

**Comment by Didou09** [comment]
However, there is one thing you could do that would be useful to this branch on the short term: if you provide the missing units and comments for all quantities that would be great, what do you think ?

you can do it the following way:
* Confirm the merge into devel to update deve
* open a dedicated issue "MissingUnits" or something like that
* Create a dedicated branch in which you simply complete the dict in _def_parameters.py (remember: a branch = a simple task, when possible)
* Once it's done, create a PR, ask someone else (me or Camille) to review and validate it
* After the merge into devel, I'll pull the changes and go on with this branch, updated

**Comment by DaluS** [comment]
Yes ! I'll do it right now

**Pull request merged**
