### PR TITLE
[#006] Separate numerical parameters

### PR DESCRIPTION
**Pull request by Didou09**
Motivation:
---------------
* As requested by @DaluS in PR #10, the `Solver.get_summary()` method now prints separately the numerical parameters (vs model parameters
* In order to facilitate understanding and code reviews, I will now try to make small PR, each dedicated to a small change, this should make it easier for you to follow (let me know if you prefer a single big PR at the end)

Main changes:
--------------------
* In `Solver.get_summary()` the numerical parameters are separated

Example:
------------
```
In [1]: import _class

In [2]: sol = _class.Solver()

In [3]: sol.set_dparam()

In [4]: sol.set_dvar()

In [5]: sol.get_summary()
Numerical param.  value  units  comment                                                   
----------------  -----  -----  ----------------------------------------------------------
Tmax              100    t      Duration of simulation                                    
Nx                1      None   Number of similar systems evolving in parrallel           
dt                0.01   t      Timestep (fixed timestep method)                          
Tstore            0.01   None   Time between storages (if StorageMode=full, it goes to dt)
Nt                10000  None   Number of temporal iteration                              
Ns                10001  None   Number of elements stored                                 
verb              True   None   flag indicating whether to print intermediate info        
storage           full   None   flag indicating which time steps to store                 
save              True   None   flag indicating whether to save output data               

Model param.  value                 units       group        comment                                                                  
------------  --------------------  ----------  -----------  -------------------------------------------------------------------------
beta          0.025                 y^-1        Population   Rate of population growth                                                
alpha         0.02                  y^-1        Population   Rate of productivity increase                                            
delta         0.005                 y^-1        Capital      Rate of capital depletion                                                
nu            3                     None        Production   Kapital to output ratio                                                  
eta           1000                  None        Production   1/(1+substituability)                                                    
b             0.5                   None        Production   capital part of the production                                           
z             1                     None        Production   Markup on salary estimation by employer                                  
r             0.03                  y^{-1}      Prices       Interest at the bank                                                     
etaP          0.192                 y^{-1}      Prices       Typical rate for inflation                                               
muP           1.3                   None        Prices       Mark-up of price                                                         
gammaP        1                     None        Prices       Money-illusion                                                           
phinul        0.04                  None        Philips      Unemployement rate at which there is no salary increase with no inflation
k0            -0.0065               None        Keen                                                                                  
k1            0.006737946999085467  None        Keen                                                                                  
k2            20                    None        Keen                                                                                  
div0          0.138                 None        Dividends    Part of GDP as dividends when pi=0                                       
div1          0.473                 None        Dividends    Slope                                                                    
g1            0.0                   None        Coupling     GLOBAL EFFECTS OF LAMBDA (Mean field)                                    
g2            0.0                   None        Coupling     WITH NEIGHBORS EFFECTS OF LAMBDA (field)                                 
muI           0.0                   NOTDONEYET  Coupling                                                                              
muN           0.0                   NOTDONEYET  Coupling                                                                              
tauR          2.0                   y           RelaxBuffer  Typical time for recruitement                                            
tauF          0.1                   y           RelaxBuffer  Typical time for firing                                                  
tauL          2.0                   y           RelaxBuffer  Typical time for employement information                                 
tauK          2.0                   y           RelaxBuffer  Typical time on new capital integration                                  
theta         2.6                   None        Gemmes       Convexity on abattement cost function                                    
dsigma        -0.001                y^{-1}      Gemmes       Variation rate of the growth of emission intensity                       
dPBS          -0.005                y^{-1}      Gemmes       Growth rate of back-stop technology price                                
dEland        -0.022                y^{-1}      Gemmes       Growth rate of land use change in CO2 emission                           
pi1           0.0                   T^{-1}      Damage       Linear temperature impact                                                
pi2           0.00236               T^{-2}      Damage       Quadratic temperature impact                                             
pi3           5.07e-06              T^{-zeta}   Damage       Weitzmann Damage temperature impact                                      
zeta          6.754                 None        Damage       Weitzmann impact                                                         
fk            0.3333333333333333    None        Damage       Fraction of environmental damage                                         
Phi12         0.024                 None        Climate      Transfer of carbon from atmosphere to biosphere                          
Phi23         0.001                 None        Climate      Transfer from biosphere to stock                                         
C             10.204081632653061    SI          Climate      Heat capacity of fast-paced climate                                      
C0            3.52                  SI          Climate      Heat capacity of inertial component of climate                           
gammaHEAT     0.0176                None        Climate      Heat exchange coefficient between layer                                  
Tsens         3.1                   T           Climate      Climate sensitivity (deltaT/log2CO2)                                     
FexoMax       0.7                   W M^{-2}    Climate      Maximal exougenous radiative forcing                                     
F2CO2         3.681                 W/m2        Climate      doubling CO2 impact on forced radiations                                 
PopSat        12                    Humans      Population   Maximal population (billions)                                            

variable  shape       units               comment                
--------  ----------  ------------------  -----------------------
a         (10000, 1)  Output Humans^{-1}  productivity per worker
N         (10000, 1)  Humans              Population             
K         (10000, 1)  Technological Unit  Capital                
W         (10000, 1)  Dollars             Salary                 
D         (10000, 1)  Dollars             Absolute private debt  
```

### CODE REVIEW

**Comment by Didou09** [comment]
Great news: the syntax checking worked!

**Comment by Didou09** [comment]
I'm not correcting the last 3 remaining suggested syntax errors by flake8 because the doc says the way it is currently written will soon be considered best practice:
image

**Comment by DaluS** [comment]
Thanks ! That work indeed, can you add comments on how to use the different functions ? 
Also I saw that you import a pandas, shouldn't it be in in requirements (even as an optional one ? )
I also assume that :
"    _MODEL = 'v0' ", "    _PARAMSET = _MODEL ", " _VARSET = 'GK' " will be entry of the class later on ?

**Comment by Didou09** [comment]
> Thanks ! That work indeed, can you add comments on how to use the different functions ?
OK I'll do it in a later PR

> Also I saw that you import a pandas, shouldn't it be in in requirements (even as an optional one ? )
Here pandas is just in vase you like to work with pandas (I don't use it most of the time), so it's up to you to decide if we keep this feature or not. 

> I also assume that :
> " _MODEL = 'v0' ", " _PARAMSET = _MODEL ", " _VARSET = 'GK' " will be entry of the class later on ?
Yes, these are temporary parameters

**Pull request merged**
