### PR TITLE
Try to fix things i dont understand

### PR DESCRIPTION
**Pull request by DaluS**
Ok now there is : 

* All my previous modifications (Newformalism etc) in the folder 
* Misc modification are going with it
* All test are working well 
* The code is almost pep compliant on everything 

There has been quite a fight between me and my code as some modification was surprisingly breaking the code. This one works well on all sides

### CODE REVIEW

**Comment by DaluS** [comment]
Now `hub.plot` gives a simple plot of all variables inside the system ! 
image

* rows give the number of row for the plot
* idx plot only the system of index idx (when multiple systems in parrallel)

**Review by Didou09 — APPROVED** [review]
I approve the PR

It seems ok, test are passing, closer to what you want.
I don't really have questions (no time, leaving for holidays in 10 min), I might come back on some parts later 

However, I do have a comment: please try to submit shorter PRs next time (14 files modified is a lot...).

This one could have been split up into at least:

* Renaming the class (and unit tests files)
* New formalism for _def_fields and model files
* adding plots (methods + files) 
* Modifying the README

All these task can be treated independently, and they should treated separately next time if possible.
Smaller PRs make life easier for everyone (easier to review by others, easier to decorrelate independent changes so if one breaks the tests we can still merge the others, easier to go back to an anterior version if we later realize we went in the wrong direction while still keeping the useful changes, easier to keep track of changes...)

Just try to keep that in mind: a single change = a single PR, even if you're just changing 10 lines of code in a single file

As far as I am concerned, the PR can be merged.
Congratulations

**Comment by DaluS** [comment]
> I approve the PR
> 
> It seems ok, test are passing, closer to what you want.
> I don't really have questions (no time, leaving for holidays in 10 min), I might come back on some parts later
> 
> However, I do have a comment: please try to submit shorter PRs next time (14 files modified is a lot...).

The reasons are multiple however it's my fault : 
* There is the pep8 compliance of all the files I had written (hence 14 files modified)
* There is the integration of all previous files that had been checked in the previous PR but not accepted (there was a test not running) 
* Most of it is comments added everywhere :) 
* The only real add is the plot which is a few lines :) 

> This one could have been split up into at least:
> 
> * Renaming the class (and unit tests files)
> * New formalism for _def_fields and model files
> * adding plots (methods + files)
> * Modifying the README
 
I agree ! In that case what I should do is : 
* One modification on a new branch 
* Send the PR 
* Do a branch on this branch, add modifications then send a new PR ? 

> All these task can be treated independently, and they should treated separately next time if possible.
> Smaller PRs make life easier for everyone (easier to review by others, easier to decorrelate independent changes so if one breaks the tests we can still merge the others, easier to go back to an anterior version if we later realize we went in the wrong direction while still keeping the useful changes, easier to keep track of changes...)
> 
> Just try to keep that in mind: a single change = a single PR, even if you're just changing 10 lines of code in a single file
> 
> As far as I am concerned, the PR can be merged.
> Congratulations

Thanks ! I'll do useful things for the code (and not only comments) now :)

**Comment by DaluS** [comment]
And the most important : I wish you great holidays ! 

I'll do my best that you have nice, well-organized PR with the good documentation when you come back, without the destruction of everything ( which was the case -almost- yesterday ! )

**Comment by Didou09** [comment]
>  One modification on a new branch
    Send the PR
    Do a branch on this branch, add modifications then send a new PR ?


If thé changes are indépendant, better do each new branch from devel

If they are not independent then yes, you do each branche from thé previous one

**Pull request merged**
