### PR TITLE
Issue064 first non regression

### PR DESCRIPTION
**Pull request by Didou09**
Motivations:
--------------
* Since PR #62 , we have the tools to check non-regression regarding output data 
* We save reference data for all models and all solvers, and from now on, when the tests will run they will load this reference output and compare to the current output, and raise an exception if there is difference

=> First non-regression tests implemented :-)

Main changes:
----------------
* In the `tests/` folder, 2 sub-folders are created:
    - `ouput_temp/` where temporary (current) output is saved (just to check the saving / loading routines work). This folder is cleaned after the tests are run
     - `output_ref/` where the reference data is stored (and preserved, not cleaned). It is loaded for comparison with the current data, to detect any difference that may be caused by recent changes
* In `_saveload.py`, several new routines had to be implemenet:
    - `_check_files()`: a single generic routine to check a file name before loading it (to check it is a valid output file name)
    - '_check_files_validity()': a sub-routine, used by the previous `_check_files()` to do the actual checks
    - `get_file_parsing()`: a routine to parse the file name (if valid) and extract its components (mode, solver, name, user, date...)
    - `get_available_output()`: a routine like `get_available_models()`, that list the existing output files in a given folder
    - `_get_available_output_check()`: a sub-routine to check the inputs provided by the user for the previous routine
* Hence, it is now possible to quickly get an overview of the existing output (as a printed message, as a `list`, as a `dict`)
* It is also possible to get the parsed components of a file
* Also, the `load()` method can now take a list of files (instead of a single file) and automatically loads all files and returns a list of instances.
* In order to discriminate the various reference output to test for non-regression, it was necessary to include the solver name in the full name of saved files, which are now of the form:
        `Output_MODEL_SOLVER_name_USER_DATE.npz`
* New unit test now check for non-regression against reference data :-)
*A minor vulnerability was removed: the order in which the functions arguments were stored was not reproducible due to the use of set(). This was detected thanks to the new unit tests described above. Fixed

Issues:
-------
* Fixes issue #64 

Examples:
-----------

In addition to the unit tests that run automatically, here is a typical use case of the new routines (on my laptop, where I have started creating / saving output):

```
In [1]: import _core                                                                                                                                

In [2]: _core._saveload.get_available_output()                                                                                                      
File selection criteria:
	- path: /Home/DV226270/Projects/GEMMES/output

Available files matching criteria:
	- /Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_placeholder_DV226270_20210723-090103.npz
	- /Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_test_DV226270_20210723-094055.npz
	- /Home/DV226270/Projects/GEMMES/output/Output_GK_eRK2-scipy_placeholder_DV226270_20210723-094128.npz
	- /Home/DV226270/Projects/GEMMES/output/Output_GK_eRK4-homemade_placeholder_DV226270_20210723-121745.npz

```

When can also use filters on the file name:
```
In [3]: _core._saveload.get_available_output(model='G-Reduced', name='test')                                                                        
File selection criteria:
	- path: /Home/DV226270/Projects/GEMMES/output
	- model: G-Reduced
	- name: test
	
Available files matching criteria:
	- /Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_test_DV226270_20210723-094055.npz
```

Like for the other similar methods, it is also possible to get the result as a list (or a dict) instead of printing it

```
In [13]: out = _core._saveload.get_available_output(returnas=list)                                                                                  

In [14]: out                                                                                                                                        
Out[14]: 
['/Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_placeholder_DV226270_20210723-090103.npz',
 '/Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_test_DV226270_20210723-094055.npz',
 '/Home/DV226270/Projects/GEMMES/output/Output_GK_eRK2-scipy_placeholder_DV226270_20210723-094128.npz',
 '/Home/DV226270/Projects/GEMMES/output/Output_GK_eRK4-homemade_placeholder_DV226270_20210723-121745.npz']
```

The dict contains the parsed components:
```
In [15]: out = _core._saveload.get_available_output(returnas=dict)                                                                                  

In [16]: out                                                                                                                                        
Out[16]: 
{'/Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_placeholder_DV226270_20210723-090103.npz': {'model': 'G-Reduced',
  'solver': 'eRK4-homemade',
  'name': 'placeholder',
  'user': 'DV226270',
  'date': '20210723-090103',
  'fmt': 'npz'},
 '/Home/DV226270/Projects/GEMMES/output/Output_G-Reduced_eRK4-homemade_test_DV226270_20210723-094055.npz': {'model': 'G-Reduced',
  'solver': 'eRK4-homemade',
  'name': 'test',
  'user': 'DV226270',
  'date': '20210723-094055',
  'fmt': 'npz'},
 '/Home/DV226270/Projects/GEMMES/output/Output_GK_eRK2-scipy_placeholder_DV226270_20210723-094128.npz': {'model': 'GK',
  'solver': 'eRK2-scipy',
  'name': 'placeholder',
  'user': 'DV226270',
  'date': '20210723-094128',
  'fmt': 'npz'},
 '/Home/DV226270/Projects/GEMMES/output/Output_GK_eRK4-homemade_placeholder_DV226270_20210723-121745.npz': {'model': 'GK',
  'solver': 'eRK4-homemade',
  'name': 'placeholder',
  'user': 'DV226270',
  'date': '20210723-121745',
  'fmt': 'npz'}}
```

### CODE REVIEW

**Comment by Didou09** [comment]
Hum... the non-regression tests are passing on my laptop but not on Github...
=> converting to draft until I fix it

**Comment by Didou09** [comment]
Fixed !

The issue was due to a small difference between github and my laptop:
* the code stores the model name in `Solver.dmisc['model']`, but it also stores the absolute path to the model file that was loaded (for tracaeability).
* It was this particular field that was different from the reference:
   - the reference files were created on my laptop (hence the path for the reference model was `/Home/DV226270/Projects/GEMMES/...`)
   - But on Github, the tests are run from a virtual machine, and the models for the current output are loaded from the github server (hence the path was something like `/home/runner/work/GEMMES/...`)
* This is inevitable, and I allowed this (and only this) difference between the current and the reference output, as it has no consequence on the numerical values of the variables.

**Comment by Didou09** [comment]
@Dalus, I am not at home today, I don't have access to Teams, if you want to do a visio contact me via Github and we'll use Skype or Jitsi (better Jitsi: online, free, no registration)

**Comment by DaluS** [comment]
@Didou09 Thank you ! 
If you are available to discuss I open this jitsi in the background https://meet.jit.si/didierpaulgemmes

**Pull request merged**
